# Generated by Django 2.0.6 on 2019-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StdId', models.IntegerField()),
                ('StdName', models.CharField(max_length=30)),
                ('StdMarks', models.FloatField()),
                ('StdAdd', models.CharField(max_length=30)),
            ],
        ),
    ]
