# Generated by Django 2.0.7 on 2019-07-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prac_id', models.IntegerField()),
                ('add', models.CharField(max_length=30)),
                ('edu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='prac1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prac1_id', models.IntegerField()),
                ('add', models.CharField(max_length=30)),
                ('edu', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
